name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . -t vishnuyadav799/wisecow-app:latest

      - name: Push Docker image
        run: |
          docker push vishnuyadav799/wisecow-app:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=vishnuyadav799/wisecow-app:latest
          kubectl rollout status deployment/wisecow-deployment


# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
      
#     - name: Login to Container Registry
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
        
#     - name: Build Docker image
#       run: docker build -t vishnuyadav799/wisecow-app:latest .
      
#     - name: Push Docker image
#       run: docker push vishnuyadav799/wisecow-app:latest
      
#     - name: Set up Kubeconfig
#       run: |
#         mkdir -p $HOME/.kube
#         echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

#     - name: Deploy to Kubernetes
#       run: kubectl apply -f wisecow-deployment.yaml --validate=false
#       env:
#         KUBECONFIG: $HOME/.kube/config
